# The numpy.random package

It returns random numbers between 0 (inclusive) and 1 (excluded). Some examples of the rand() function.

In [1]:
import numpy as np

Without arguments returns a single random number.

In [2]:
np.random.rand()

0.24896471753715022

With one argument, returns one row of the specified amount of random numbers

In [3]:
np.random.rand(4)

array([0.49550694, 0.21749301, 0.73402437, 0.14174958])

Two or more arguments specify the dimensions of a random number matrix of n dimensions.  
The following example creates a 3rows x 2columns bi-dimensional matrix of random numbers.

In [4]:
np.random.rand(3,2)

array([[0.08284295, 0.67350741],
       [0.95183378, 0.7237853 ],
       [0.15749176, 0.64783086]])

This is for a 3 dimensinal matrix

In [5]:
np.random.rand(2,3,4)

array([[[0.16493296, 0.55177679, 0.93533363, 0.18514949],
        [0.21498481, 0.43712128, 0.1723712 , 0.35612051],
        [0.19987208, 0.6887394 , 0.68184549, 0.96221192]],

       [[0.38314483, 0.46694113, 0.42666553, 0.8926507 ],
        [0.60392027, 0.58396475, 0.17571619, 0.01192805],
        [0.19084021, 0.82171933, 0.97729746, 0.07279342]]])

More dimensions can be added:

In [6]:
np.random.rand(2,3,4,5)

array([[[[0.57421865, 0.31365385, 0.03236531, 0.48568966, 0.1774274 ],
         [0.95378463, 0.23870675, 0.02065991, 0.26433774, 0.84795531],
         [0.90991802, 0.37014324, 0.59836439, 0.69219678, 0.2967858 ],
         [0.47921009, 0.57418427, 0.60608347, 0.29776858, 0.28173231]],

        [[0.91341407, 0.06351589, 0.78722134, 0.76266257, 0.88497468],
         [0.04514735, 0.36775966, 0.92099076, 0.5020583 , 0.18741058],
         [0.06846699, 0.50460459, 0.63209956, 0.83278366, 0.53643922],
         [0.82759128, 0.99408477, 0.74030839, 0.2124065 , 0.03257856]],

        [[0.40195554, 0.70119619, 0.39766939, 0.29177925, 0.19775233],
         [0.12930698, 0.74061103, 0.92498008, 0.57540403, 0.45408301],
         [0.33041708, 0.57668063, 0.68770902, 0.52440697, 0.43432554],
         [0.90816936, 0.26244822, 0.83652978, 0.49326176, 0.54965778]]],


       [[[0.84111458, 0.79841752, 0.1797242 , 0.29248243, 0.15715123],
         [0.62903023, 0.43763012, 0.60128   , 0.67970051, 0.30369123]

In [7]:
np.random.uniform(0.0, 100.0)

0.5750700287578292